---
#Ssh server config vars
sshd_allowed_users: root
sshd_auth_methods: publickey
sshd_ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
sshd_hostkeyalgorithms: ssh-ed25519,ssh-ed25519-cert-v01@openssh.com
sshd_kexalgorithms: curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
sshd_listen_address: "{{ ansible_default_ipv4.address }}"
sshd_macs: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
sshd_password_authentication: no
sshd_permit_root_login: prohibit-password
sshd_port: 22
sshd_pubkeyacceptedkeytypes: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
sshd_usedns: no
sshd_restart_handler_state: restarted


sshd_moduli_file: '/etc/ssh/moduli'
#Use Group 15(3072-bit) and above for DH moduli
sshd_moduli_minimum: 3071

replace_host_keys: no
# not yet implemented regenerate_dh_keys: no
