---
all:
  hosts:
    ubuntu-temp:
      ansible_user: ttyrawa
  children:
    bare_metal:
      hosts:
        dns:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
      children:
        edge:
          hosts:
            erx:
            sw8:
        pve_nodes:
          hosts:
            pve[1:4]:
    virtual:
      hosts:
        media:
        ubnt:
        rancher:
        nas:
        home:
      children:
        kube_nodes:
          hosts:
            kube[1:3]:
    servers:
      children:
        pve_nodes:
        virtual:
        hosts:
          dns: