---
#task list to configure free repos and remove sub pop up
- name: comment out Enterprise Repo
  replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '(^deb.*)'
    replace: '#\1'
- name: add non-sub repos to apt
  apt_repository:
    repo: 'deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription'
    state: present
    filename: pve-no-sub
- name: apt upgrade
  apt:
    update_cache: yes
    upgrade: dist
- name: modify line which performs license check
  replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: "data.status \\!== \\'Active\\'"
    replace: "false"
    backup: yes
  notify: restart pveproxy