- name: Check if ssh moduli contains weak DH parameters
  shell: awk '$5 < {{ sshd_moduli_minimum }}' {{ sshd_moduli_file }}
  register: sshd_register_moduli
  changed_when: false
  check_mode: no

- name: remove all small primes
  shell: >
        awk '$5 >= {{ sshd_moduli_minimum }}' {{ sshd_moduli_file }} > {{ sshd_moduli_file }}.new ;
        [ -r {{ sshd_moduli_file }}.new -a -s {{ sshd_moduli_file }}.new ] 
        && mv {{ sshd_moduli_file }}.new {{ sshd_moduli_file }} || true
  notify: restart sshd
  when:
    - sshd_register_moduli.stdout